### ISSUE TITLE
Error on Delete

### ISSUE THREAD

**Issue by bearnst** [PaloAltoNetworks/pan-os-python#176]
After deleting several security rules, I get the following error:

Traceback (most recent call last):
  File "C:\Users\bearnst\PycharmProjects\untitled\venv\lib\site-packages\pandevice\base.py", line 3447, in method
    super_method(self, *args, **kwargs)
  File "C:\Users\bearnst\PycharmProjects\untitled\venv\lib\site-packages\pan\xapi.py", line 733, in delete
    self.__type_config('delete', query, extra_qs)
  File "C:\Users\bearnst\PycharmProjects\untitled\venv\lib\site-packages\pan\xapi.py", line 805, in __type_config
    raise PanXapiError(self.status_detail)
pan.xapi.PanXapiError: ElementTree.fromstring ParseError: no element found: line 1, column 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/bearnst/PycharmProjects/untitled/Test", line 78, in <module>
    rule.delete()
  File "C:\Users\bearnst\PycharmProjects\untitled\venv\lib\site-packages\pandevice\base.py", line 597, in delete
    device.active().xapi.delete(self.xpath(), retry_on_peer=self.HA_SYNC)
  File "C:\Users\bearnst\PycharmProjects\untitled\venv\lib\site-packages\pandevice\base.py", line 3464, in method
    raise the_exception
pandevice.errors.PanDeviceXapiError: ElementTree.fromstring ParseError: no element found: line 1, column 0

If there something I am doing wrong?

**Comment by shinmog** [comment]
Do you have some code you can share that I can use to repro this?

**Comment by shinmog** [comment]
Seems this is no longer an issue, been a few years at this point.  Closing this out.
