### ISSUE TITLE
device.Telemetry not compatible with PanOS 10.x

### ISSUE THREAD

**Issue by markharden817** [PaloAltoNetworks/pan-os-python#353]
## Describe the bug

PANOS version 10.x uses a different XPATH and schema for telemetry configuration.  device.Telemetry not compatible with PanOS 10.x

```xml
<device-telemetry>
	<threat-prevention>yes</threat-prevention>
	<device-health-performance>yes</device-health-performance>
	<product-usage>yes</product-usage>
	<region>americas</region>
</device-telemetry>
```

## Expected behavior

```python
from panos.device import Telemetry

new_telemetry_params = {
    'threat_prevention': True,
    'device_health-performance': True,
    'product_usage': True,
    'region': 'americas',
}
new_telemetry_obj = Telemetry(**new_telemetry_params)
fw.add(new_telemetry_obj)
new_telemetry_obj.apply()
```

Should configure device telemetry settings on PANOS 10.x device.

## Current behavior
Unable to configure device telemetry settings.

### Using new params:
```python
Traceback (most recent call last):
  File "C:\Users\Mark\AppData\Roaming\JetBrains\PyCharmCE2021.1\scratches\scratch.py", line 25, in <module>
    new_telemetry_obj = Telemetry(**new_telemetry_params)
  File "C:\Users\Mark\Documents\projects\pan-os-python\panos\base.py", line 2328, in __init__
    raise ValueError('No param "{0}" exists'.format(name))
ValueError: No param "threat_prevention" exists
```

### Using old params:
```python
Traceback (most recent call last):
  File "C:\Users\Mark\AppData\Roaming\JetBrains\PyCharmCE2021.1\scratches\scratch.py", line 41, in <module>
    old_telemetry_obj.apply()
  File "C:\Users\Mark\Documents\projects\pan-os-python\panos\base.py", line 604, in apply
    device.active().xapi.edit(
  File "C:\Users\Mark\Documents\projects\pan-os-python\panos\base.py", line 3673, in method
    raise the_exception
panos.errors.PanDeviceXapiError: Could not get schema node for xpath /config/devices/entry[@name='localhost.localdomain']/update-schedule/statistics-service
```
## Possible solution

Add 10.0 and 10.1 version support

## Steps to reproduce

```python
from panos.device import Telemetry

HOSTNAME = os.environ["PAN_HOSTNAME"]
USERNAME = os.environ["PAN_USERNAME"]
PASSWORD = os.environ["PAN_PASSWORD"]
fw = Firewall(HOSTNAME, USERNAME, PASSWORD)

new_telemetry_params = {
    'threat_prevention': True,
    'device_health-performance': True,
    'product_usage': True,
    'region': 'americas',
}
new_telemetry_obj = Telemetry(**new_telemetry_params)
fw.add(new_telemetry_obj)
new_telemetry_obj.apply()
```

## Context

Have to deal with annoying pop up asking me to configure telemetry

## Your Environment
PA systems:
  - PA-850
  - PAVM-100

pan-os-python: 1.0.2
python: 3.9.1

**Comment by shinmog** [comment]
@markharden817 

This is incorrect config.  If you look at the `CHILDTYPES` you'll notice that `device.Telemetry` does not show up as a child type for `firewall.Firewall`; it shows up as a child type for `device.SystemSettings`.

Thus your object hierarchy should be `firewall.Firewall` > `device.SystemSettings` > `device.Telemetry`.
