### ISSUE TITLE
Able to get system info, but unable to get arp table

### ISSUE THREAD

**Issue by RobertoMD** [PaloAltoNetworks/pan-os-python#393]
Hi,
I'm using python 3.9.2, pano-os-python 1.6.0, pan-python 0.16.0
device version is 'sw-version': '8.1.18'

I'm able to get system info as per the SDK examples, e.g.:

```
from panos.firewall import Firewall
fw = Firewall ('device_ip', api_username='username', api_password = 'password')
resp = fw.op('show system info')

```
This works as expected, and I'm able to get the output of the command.

however, if I replace "show system info" with "show arp all", I'm getting this error:

Traceback (most recent call last):
  File "c:\Users\roberto\pythonpalo\env\lib\site-packages\panos\base.py", line 3661, in method
    super_method(self, *args, **kwargs)
  File "c:\Users\roberto\pythonpalo\env\lib\site-packages\pan\xapi.py", line 951, in op
    self.__type_op(cmd, vsys, extra_qs)
  File "c:\Users\roberto\pythonpalo\env\lib\site-packages\pan\xapi.py", line 974, in __type_op
    raise PanXapiError(self.status_detail)
pan.xapi.PanXapiError:  show -> arp -> all has unexpected text.
 show -> arp  is unexpected
 show  is unexpected

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\roberto\pythonpalo\pythonpalo\testpalo.py", line 19, in <module>
    res=fw.op('show arp all')
  File "c:\Users\roberto\pythonpalo\env\lib\site-packages\panos\firewall.py", line 219, in op
    return super(Firewall, self).op(
  File "c:\Users\roberto\pythonpalo\env\lib\site-packages\panos\base.py", line 3822, in op
    element = self.xapi.op(
  File "c:\Users\roberto\pythonpalo\env\lib\site-packages\panos\base.py", line 3682, in method
    raise the_exception
panos.errors.PanDeviceXapiError:  show -> arp -> all has unexpected text.
 show -> arp  is unexpected
 show  is unexpected

Using an ssh connection, I'm able to get results for both commands.
Any help would be greatly appreciated.

**Comment by shinmog** [comment]
If you SSH to PAN-OS and run the following:

```
debug cli on
show arp all
```

You see that PAN-OS is actually formatting the call like this:

```xml
<request cmd="op" cookie="2801768344648204" uid="1000"><operations><show><arp><entry name='all'/></arp></show></operations></request>
```

Removing the cruft from that, what you'd need to send is this:

```xml
<show><arp><entry name='all'/></arp></show>
```

pan-os-python does do some auto formatting with `op` commands, but formatting things as an entry is not a format that can be automatically converted to.  So you'll have to do this yourself:

```python
cmd = "<show><arp><entry name='all'/></arp></show>"
ans = fw.op(txt, cmd_xml=False)
```
