### ISSUE TITLE
update content package is not functional with version string

### ISSUE THREAD

**Issue by kevinhuy** [PaloAltoNetworks/pan-os-python#394]
## Describe the bug

    fw = firewall.Firewall(hostname="", username="")    
    updater.ContentUpdater(fw).check()
    updater.ContentUpdater(fw).download()
    updater.ContentUpdater(fw).install(version="8503-7125", sync=True)

## Expected behavior

execute without error

## Current behavior

Traceback (most recent call last):
  File "test_update_content.py", line 41, in <module>
    main()
  File "test_update_content.py", line 37, in main
    install_content = updater.ContentUpdater(fw).install(version="8503-7125", sync=True)
  File "/home/kevin/.pyenv/versions/panos/lib/python3.8/site-packages/panos/updater.py", line 544, in install
    response = self._op(op)
  File "/home/kevin/.pyenv/versions/panos/lib/python3.8/site-packages/panos/updater.py", line 38, in _op
    return self.pandevice.xapi.op(cmd, cmd_xml=True)
  File "/home/kevin/.pyenv/versions/panos/lib/python3.8/site-packages/panos/base.py", line 3682, in method
    raise the_exception
panos.errors.PanDeviceXapiError:  request -> content -> upgrade -> install -> version '8503-7125' is not an allowed keyword
 request -> content -> upgrade -> install -> version is invalid

## Possible solution

with keyword latest it work without issue.
updater.ContentUpdater(fw).install(version="latest", sync=True)

**Comment by shinmog** [comment]
Is "9503-7125" downloaded before you try to invoke `.install(version="9503-7125")`?

**Comment by kevinhuy** [comment]
Hi

Yes was already downloaded before the try.

Thks
