### ISSUE TITLE
How to get all shared address object?

### ISSUE THREAD

**Issue by hustlibraco** [PaloAltoNetworks/pan-os-python#427]
If I assign device group to "Test", I will get my expect.
```
from panos import panorama, objects
from apps.panorama.linux import core, config
pm = core.PanoramaManager(config.HOSTNAME, config.USERNAME, config.PASSWORD)
device_group = panorama.DeviceGroup("Test")
pm.pano.add(device_group)
device_group.refresh()
addrs = pm.pano.findall(objects.AddressObject, recursive=True)
print(addrs)

## output
[<AddressObject 10.0.76.17 0x7f958b7c1940>, <AddressObject 10.0.79.217 0x7f958b8724f0>]
```

When I assign device group to "shared", It will raise an error that I'm confused.
```
from panos import panorama, objects
from apps.panorama.linux import core, config
pm = core.PanoramaManager(config.HOSTNAME, config.USERNAME, config.PASSWORD)
device_group = panorama.DeviceGroup("shared")
pm.pano.add(device_group)
device_group.refresh()
addrs = pm.pano.findall(objects.AddressObject, recursive=True)
print(addrs)

# output
Traceback (most recent call last):
  File "scripts/test_feature.py", line 197, in <module>
    cli()
  File "/root/repo/invoker/.venv/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/root/repo/invoker/.venv/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/root/repo/invoker/.venv/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/root/repo/invoker/.venv/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/repo/invoker/.venv/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "scripts/test_feature.py", line 152, in test_panorama_address
    device_group.refresh()
  File "/root/repo/invoker/.venv/lib/python3.8/site-packages/panos/base.py", line 849, in refresh
    xml = self._refresh_xml(running_config, exceptions, refresh_children)
  File "/root/repo/invoker/.venv/lib/python3.8/site-packages/panos/base.py", line 1039, in _refresh_xml
    raise err.PanObjectMissing(err_msg, pan_device=dev)
panos.errors.PanObjectMissing: Object doesn't exist: /config/devices/entry[@name='localhost.localdomain']/device-group/entry[@name='shared'
```

I'm sure I have many shared address, How to get them by this SDK?
![image](https://user-images.githubusercontent.com/5344453/157661931-6d14e640-6c59-4834-ab4b-a135a547ceb4.png)

**Comment by rebelfish** [comment]
Shared is not a device group so you leave off the device group portion.

**Comment by hustlibraco** [comment]
> Shared is not a device group so you leave off the device group portion.

I have tried to remove device_group part, and I get no result. Can you give me sample code?

**Comment by rebelfish** [comment]
The only option I know is:
```python
from panos.panorama import Panorama
from panos.objects import AddressObject

pano = Panorama(hn, un, pw)
AddressObject.refreshall(pano)
addr = pano.findall(AddressObject)
```

**Comment by hustlibraco** [comment]
> The only option I know is:
> 
> ```python
> from panos.panorama import Panorama
> from panos.objects import AddressObject
> 
> pano = Panorama(hn, un, pw)
> AddressObject.refreshall(pano)
> addr = pano.findall(AddressObject)
> ```

It works! Thank you very much.
