### ISSUE TITLE
Modifie calls fail on DeviceGroup when FW is a child

### ISSUE THREAD

**Issue by Coo101** [PaloAltoNetworks/pan-os-python#501]
## Describe the bug
When trying to do a call for a devicegroup that modifies the live device and a Firewall object is attached it errors out
TypeError: Firewall.element() got an unexpected keyword argument 'comparable'

## Expected behavior

update the device

## Current behavior

Even a simple refresh and apply fails

## Steps to reproduce

devicegroup= DeviceGroup('dg-name')
panorama.add(devicegroup)
devicegroup.refresh()
devicegroup.apply() 

## Screenshots

Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm 2022.2\plugins\python\helpers\pydev\_pydevd_bundle\pydevd_exec2.py", line 3, in Exec
    exec(exp, global_vars, local_vars)
  File "<input>", line 1, in <module>
  File "%localpath%\Anaconda3\envs\KNIME\Lib\site-packages\panos\base.py", line 625, in apply
    self.xpath(), self.element_str(), retry_on_peer=self.HA_SYNC
                  ^^^^^^^^^^^^^^^^^^
  File "%localpath%\Anaconda3\envs\KNIME\Lib\site-packages\panos\base.py", line 535, in element_str
    return ET.tostring(self.element(), encoding="utf-8")
                       ^^^^^^^^^^^^^^
  File "%localpath%\Anaconda3\envs\KNIME\Lib\site-packages\panos\base.py", line 2606, in element
    self.xml_merge(ans, itertools.chain(*iterchain))
  File "%localpath%\Anaconda3\envs\KNIME\Lib\site-packages\panos\base.py", line 1694, in xml_merge
    for e in elements:
  File "%localpath%\Anaconda3\envs\KNIME\Lib\site-packages\panos\base.py", line 574, in _subelements
    e.append(child.element(comparable=comparable))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Firewall.element() got an unexpected keyword argument 'comparable'

## Your Environment

Using Anaconda3

- Version used: 1.7.3
- Environment name and version: python 3.11.2
- Operating System and version (desktop or mobile): Windows10

**Comment by tstarck** [comment]
I'm running into this same issue or at least exactly the same error condition when trying to manage firewall security rules with pan-os SDK. I'm using SDK version 1.12.1.

I'm not sure if I'm doing something wrong, but the error message itself is not helping me.

Are there any developments with this issue or could someone guide me to a documentation I might have missed?
